---
name: Release challenge-app

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:

  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify -Pintegration-test

  determine-version:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.versioning.outputs.release_tag }}
    steps:
      - name: Determine Version
        id: versioning
        run: |
          if [[ $GITHUB_EVENT_NAME == 'release' ]]; then
            echo "release_tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "release_tag=0.0.0-dev" >> $GITHUB_OUTPUT
          fi


  build-push:
    needs: [test, determine-version]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: drmendes/challenge-app:${{ needs.determine-version.outputs.release_tag }}